# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       plasma-desktop

# >> macros
# << macros

Summary:    Plasma 5 desktop
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  plasma-desktop.yaml
Source101:  plasma-desktop-rpmlintrc
Requires:   kf5-filesystem
Requires:   plasma-workspace
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5QuickWidgets)
BuildRequires:  pkgconfig(Qt5Svg)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(libusb)
BuildRequires:  pkgconfig(fontconfig)
BuildRequires:  pkgconfig(x11-xcb)
BuildRequires:  pkgconfig(xkbfile)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(xrender)
BuildRequires:  pkgconfig(xcb)
BuildRequires:  pkgconfig(xcb-composite)
BuildRequires:  pkgconfig(xcb-damage)
BuildRequires:  pkgconfig(xcb-dpms)
BuildRequires:  pkgconfig(xcb-dri2)
BuildRequires:  pkgconfig(xcb-glx)
BuildRequires:  pkgconfig(xcb-randr)
BuildRequires:  pkgconfig(xcb-record)
BuildRequires:  pkgconfig(xcb-render)
BuildRequires:  pkgconfig(xcb-res)
BuildRequires:  pkgconfig(xcb-screensaver)
BuildRequires:  pkgconfig(xcb-shape)
BuildRequires:  pkgconfig(xcb-shm)
BuildRequires:  pkgconfig(xcb-sync)
BuildRequires:  pkgconfig(xcb-xevie)
BuildRequires:  pkgconfig(xcb-xf86dri)
BuildRequires:  pkgconfig(xcb-xfixes)
BuildRequires:  pkgconfig(xcb-xinerama)
BuildRequires:  pkgconfig(xcb-xprint)
BuildRequires:  pkgconfig(xcb-xtest)
BuildRequires:  pkgconfig(xcb-xv)
BuildRequires:  pkgconfig(xcb-xvmc)
BuildRequires:  pkgconfig(xcb-atom)
BuildRequires:  pkgconfig(xcb-aux)
BuildRequires:  pkgconfig(xcb-event)
BuildRequires:  pkgconfig(xcb-icccm)
BuildRequires:  pkgconfig(xcb-image)
BuildRequires:  pkgconfig(xcb-keysyms)
BuildRequires:  pkgconfig(xcb-renderutil)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  phonon-qt5-devel
BuildRequires:  plasma-devel
BuildRequires:  kdoctools-devel
BuildRequires:  ki18n-devel
BuildRequires:  kcmutils-devel
BuildRequires:  knewstuff-devel
BuildRequires:  kdelibs4support-devel
BuildRequires:  knotifyconfig-devel
BuildRequires:  kdesu-devel
BuildRequires:  attica-devel
BuildRequires:  kwallet-devel
BuildRequires:  krunner-devel
BuildRequires:  libksysguard-devel
BuildRequires:  plasma-workspace-devel
BuildRequires:  kwin-devel
BuildRequires:  kactivities-libs-devel
BuildRequires:  desktop-file-utils

%description
Plasma 5 desktop


%package shell
Summary:    Plasma desktop shell
Group:      System/GUI/Other
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}

%description shell
Plasma desktop shell.


%package doc
Summary:    Documentation and user manuals for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
Documentation and user manuals for %{name}


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
rm -vf %{buildroot}%{_kf5_libdir}/libkfontinst{,ui}.so || true

# Hide knetattach from the applications menu
cat >> %{buildroot}%{_kf5_sharedir}/applications/knetattach.desktop <<EOF
NoDisplay=true
EOF
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%dir %{_kf5_sharedir}/plasma/shells
%{_kf5_bindir}/*
%{_kf5_libdir}/libexec/*
%{_kf5_qmldir}/org/kde/plasma/private
%{_kf5_libdir}/libkdeinit5_kaccess.so
%{_kf5_libdir}/kconf_update_bin/*
%{_kf5_plugindir}/*
%{_kf5_sharedir}/plasma/*
%{_kf5_sharedir}/kdm/*
%exclude %{_kf5_sharedir}/plasma/shells/*
%{_kf5_sharedir}/config.kcfg
%{_kf5_sharedir}/*
%{_kf5_sysconfdir}/dbus-1/system.d/*.conf
%{_kf5_configdir}/*.knsrc
%{_kf5_servicesdir}/*
%{_kf5_servicetypesdir}/*
%{_datadir}/knotifications5/*.notifyrc
%{_datadir}/applications/*.desktop
%{_datadir}/dbus-1/*
%{_datadir}/polkit-1/actions/*.policy
# >> files
# << files

%files shell
%defattr(-,root,root,-)
%{_kf5_sharedir}/plasma/shells/org.kde.plasma.desktop/*
# >> files shell
# << files shell

%files doc
%defattr(-,root,root,-)
%{_kf5_htmldir}/en/*
# >> files doc
# << files doc
